library(RMySQL)
library(igraph)
dir<-getwd()
setwd(dir)
args <- commandArgs(TRUE)
mydb <- dbConnect(MySQL(), user='root', password='', dbname='social_network', host='localhost')
rs<-dbSendQuery(mydb, "select f1 from friends")
f1 = fetch(rs, n=-1)
dbClearResult(rs)
rs<-dbSendQuery(mydb, "select f2 from friends")
f2 = fetch(rs, n=-1)
dbClearResult(rs)
C<-NULL
len<-dbGetQuery(mydb,"SELECT COUNT(*) FROM friends;")
for(i in 1:len[1,1])
  C <- append(C,c(f1[i,1],f2[i,1]))
I<-unique(C, incomparables = FALSE)
I<-paste(C,collapse=",")
rs<-dbSendQuery(mydb, paste("SELECT user_id FROM users WHERE user_id not in (",paste(I),")"))
f1 = fetch(rs, n=-1)
dbClearResult(rs)
mynw <- graph(edges=C,isolates=f1[,1],directed=FALSE)
png(filename="graph.png",width=1000,height=1000)
plot(mynw)
title(main="ConnectMe Users Relation:")
dev.off()
dbDisconnect(mydb)